import '~/styles/globals.css';

import { Inter } from 'next/font/google';
import { headers } from 'next/headers';

import { TRPCReactProvider } from '~/trpc/react';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata = {
  title: 'Locker Hub',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider headers={headers()}>{children}</TRPCReactProvider>

        {/* Create navigation bar */}
        <div className="flex flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
          <div className="flex flex-row items-center justify-center">
            <div className="flex flex-row items-center justify-center">
              <img src="/lockerhublogo.png" alt="Locker Hub Logo" className="h-20 w-20" />
              <h1 className="text-6xl font-bold">Locker Hub</h1>
            </div>
          </div>
        </div>





      </body>
    </html>
  );
}
